### ISSUE TITLE
add docker compose file

### ISSUE THREAD

**Issue by emillipede** [Public-Tree-Map/public-tree-map-data-pipeline#76]
use docker compose (and maybe automated builds in github?)

**Comment by greysonp** [comment]
Github Actions looks pretty neat, and has the crucial feature needed to handle nightly deploys: cron-style scheduling: 
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule

I haven't seen any need to use Docker Compose though. In general, if you want to dockerize the setup, just create a single image that has the packages you need pre-installed (notably, `node` and `python`) and allows you to mount your current directory as a volume, then you can just do stuff like:

`docker run -v $(pwd):/project <image name> make release`

But honestly, node and python are such common packages to have installed, it's usually not a huge deal for people to just run `npm install` and whatever the python equivalent is.

Hope all is well! Site is looking great :)

**Comment by captainrandom** [comment]
@greysonp For our case it's not that hard, but it can get out of hand when you have many volumes, environment variables, command overrides, and working dir overrides.

We are trying to accomplish these 2 high level priorities to ease on-boarding new people as much as possible:

1. Make things simple to run code (one button click)
2. Everything must be cross-platform compatible (mac, linux, and windows)

When aliasing docker build/run/push/pull with a hand full of bash or makefile targets would solve 1, but doesn't solve 2. Docker-compose solves both 1 & 2 by hiding the abstracting away the complexity, not repeating myself, and its cross-platform.

Granted I've used a single docker image because circleci basically requires it, as they don't support volumes. I'd rather use 2 separate docker images, 1 for node and 1 for python, as it is the generally accepted standard: https://stackoverflow.com/questions/48787524/multiple-languages-in-docker-container

As surprising as this may be, running `npm install` and `pip install` was so complicated that on-boarding was a practical impossibility. Dependencies in the geo space are notoriously hard to install.

**Comment by captainrandom** [comment]
@emillipede I've added the docker-compose file in PR #69

**Comment by greysonp** [comment]
Yeah, I guess in general, I'd just be cautious adding more complexity to the build process. The more layers, the more knowledge that's required to maintain and edit it.

The node stuff always just worked, and setup doesn't get much easier than `npm install`. 

The only thing I ever actually had real problems with was python, and maybe that could be solved with better documentation, who knows. I don't think the python setup was ever documented in the README.

Regardless, best of luck!
